# Generated by Django 4.2.20 on 2025-04-15 15:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Recent', 'Gần đây'), ('Popular', 'Phổ biến')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Công khai'), ('0', 'Bản nháp')], default=0, max_length=1),
        ),
        migrations.CreateModel(
            name='PostVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_number', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_category', to='HOME.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='HOME.post')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
