# Generated by Django 4.2.20 on 2025-04-15 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0002_alter_post_section_alter_post_status_postversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
