# Generated by Django 4.2.20 on 2025-05-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_postversion_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Popular', 'Phổ biến'), ('Recent', 'Gần đây')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Bản nháp'), ('1', 'Công khai')], default=0, max_length=1),
        ),
    ]
